// Code generated by kernel/cbus/gen. DO NOT EDIT.
package protocol

import (
	"encoding/json"
	"fmt"
)

const ProtocolVersion = 3

type MessageType string

const (
	MessageSupervisorRegistration    MessageType = "supervisor_registration"
	MessageHeartbeat                 MessageType = "heartbeat"
	MessageStartWorker               MessageType = "start_worker"
	MessageStopWorker                MessageType = "stop_worker"
	MessageWorkerStateChange         MessageType = "worker_state_change"
	MessageWorkerLogEvent            MessageType = "worker_log_event"
	MessageWorkerInvoke              MessageType = "worker_invoke"
	MessageWorkerResult              MessageType = "worker_result"
	MessageJobStart                  MessageType = "job_start"
	MessageJobResult                 MessageType = "job_result"
	MessageServicePoolConfiguration  MessageType = "service_pool_configuration"
	MessageServiceWorkerScaleRequest MessageType = "service_worker_scale_request"
	MessageServiceOpenapi            MessageType = "service_openapi"
	MessageRuntimeDrain              MessageType = "runtime_drain"
	MessageRuntimeShutdown           MessageType = "runtime_shutdown"
	MessageAdminCommand              MessageType = "admin_command"
	MessageAdminResult               MessageType = "admin_result"
	MessageDatabaseExecute           MessageType = "database_execute"
	MessageDatabaseResult            MessageType = "database_result"
	MessageErrorResponse             MessageType = "error_response"
)

var validMessageTypes = map[MessageType]bool{
	MessageSupervisorRegistration:    true,
	MessageHeartbeat:                 true,
	MessageStartWorker:               true,
	MessageStopWorker:                true,
	MessageWorkerStateChange:         true,
	MessageWorkerLogEvent:            true,
	MessageWorkerInvoke:              true,
	MessageWorkerResult:              true,
	MessageJobStart:                  true,
	MessageJobResult:                 true,
	MessageServicePoolConfiguration:  true,
	MessageServiceWorkerScaleRequest: true,
	MessageServiceOpenapi:            true,
	MessageRuntimeDrain:              true,
	MessageRuntimeShutdown:           true,
	MessageAdminCommand:              true,
	MessageAdminResult:               true,
	MessageDatabaseExecute:           true,
	MessageDatabaseResult:            true,
	MessageErrorResponse:             true,
}

type Envelope struct {
	ProtocolVersion int             `json:"protocol_version"`
	MessageType     MessageType     `json:"message_type"`
	RuntimeGroupID  string          `json:"runtime_group_id"`
	CorrelationID   string          `json:"correlation_id,omitempty"`
	Payload         json.RawMessage `json:"payload,omitempty"`
}

func (e Envelope) Validate() error {
	if e.ProtocolVersion != ProtocolVersion {
		return fmt.Errorf("unsupported runtime protocol version %d", e.ProtocolVersion)
	}
	if !validMessageTypes[e.MessageType] {
		return fmt.Errorf("unknown runtime message type %q", e.MessageType)
	}
	if e.RuntimeGroupID == "" {
		return fmt.Errorf("runtime_group_id is required")
	}
	return nil
}
