key = "service.default.minimum_workers"
type = "integer"
storage = "node"
default = 1
environment = "KERNEL_SERVICE_DEFAULT_MINIMUM_WORKERS"
minimum = 0
maximum = 128
runtime_mutable = false
restart_required = true
description = "Default minimum Workers in a service pool."
