// Code generated by kernel/cbus/gen. DO NOT EDIT.
export const PROTOCOL_VERSION = 1 as const;

export const MESSAGE_TYPES = [
  "supervisor_registration",
  "heartbeat",
  "start_worker",
  "stop_worker",
  "worker_state_change",
  "worker_log_event",
  "worker_invoke",
  "worker_result",
  "persistent_execution_complete",
  "persistent_execution_completed",
  "job_start",
  "job_result",
  "service_pool_configuration",
  "service_worker_scale_request",
  "service_openapi",
  "runtime_drain",
  "runtime_shutdown",
  "auth_bootstrap_login",
  "auth_logout_current",
  "auth_result",
  "admin_command",
  "admin_result",
  "database_execute",
  "database_result",
  "error_response",
] as const;

export type MessageType = (typeof MESSAGE_TYPES)[number];

export interface Envelope<T = Record<string, unknown>> {
  protocol_version: typeof PROTOCOL_VERSION;
  message_type: MessageType;
  runtime_group_id: string;
  correlation_id?: string;
  payload?: T;
}

export function assertEnvelope(value: unknown): asserts value is Envelope {
  if (typeof value !== "object" || value === null) {
    throw new TypeError("runtime message must be an object");
  }
  const message = value as Record<string, unknown>;
  if (message.protocol_version !== PROTOCOL_VERSION) {
    throw new TypeError(
      `unsupported runtime protocol version ${message.protocol_version}`,
    );
  }
  if (!MESSAGE_TYPES.includes(message.message_type as MessageType)) {
    throw new TypeError(`unknown runtime message type ${message.message_type}`);
  }
  if (
    typeof message.runtime_group_id !== "string" ||
    message.runtime_group_id.length === 0
  ) throw new TypeError("runtime_group_id is required");
}
